### ISSUE TITLE
Support initializing dapr in a user provided directory

### ISSUE THREAD

**Issue by mikeb26** [dapr/cli#1056]
## Describe the proposal

Currently in standalone mode dapr cli will install the dapr runtime binaries into $HOME/.dapr. However, in some environments $HOME is readonly or os.UserHomeDir() can fail (e.g. AWS Lambda). This issue is tracking adding support for such environments. In order to support these environments I am proposing:

     1. When os.UserHomeDir() fails the change the default install location from $HOME/.dapr to /usr/local/dapr
    
      2. Allow the user to specify install location with a new --install-dir flag to both init & uninstall subcommands
    
      3. Employ the user's $PATH to find the dapr runtime binaries rather than assume they can be found in the default install location. If e dapr runtime binaries cannot be found in $PATH, fallback to the existing behavior of looking in the default install location.

## Release Note
RELEASE NOTE: **ADD** Support the dapr runtime in AWS Lambda

**Comment by shubham1172** [comment]
Thanks @mikeb26 for putting this together! A couple of thoughts - 

### Implicit vs explicit error handling

>  When os.UserHomeDir() fails the change the default install location from $HOME/.dapr to /usr/local/dapr

Should we do this implicit handling? This can be surprising for users who'd expect installation to be in `$HOME/.dapr`, or maybe installation in `/usr/local/dapr` is undesired. We can just throw an error and redirect them to the new flag `--install-dir`. Thoughts?

### Environment variable along with CLI flag

What if we use `$DAPR_PATH` along with `--install-dir` (higher precedence to CLI flag than environment variable)? This will allow us to not force users to specify `--install-dir` flag during init/uninstall.

### Using a global flag instead

Instead of using `--install-dir` for specific commands like init and uninstall, and then using `$PATH` to lookup the bin for other commands like run, version, dashboard, etc., how about we use a global flag `--dapr-path`? 

1. This can go along with the `$DAPR_PATH` env variable above. 
1. We won't have to look up the entire `$PATH` each time we run some Dapr commands
1. In future, if we decide to keep multiple Dapr installations (as in #1035), we can have different Dapr commands interact with different such directories. Having this approach should also pave the path for the same.

**Comment by pravinpushkar** [comment]
IMO Having user to always specify `--install-dir` to interact with changed custom installation dir can be little cumbersome. How about we go with only `environment variable` approach. User can set this config in his terminal configurations and the commands can be same as before. Thoughts ?

**Comment by shubham1172** [comment]
> IMO Having user to always specify `--install-dir` to interact with changed custom installation dir can be little cumbersome. How about we go with only `environment variable` approach. User can set this config in his terminal configurations and the commands can be same as before. Thoughts ?

If environment variable is specified, the CLI flag won't be required. The CLI flag can still be present and it will override the environment variable if present. 

Example scenario when CLI flag will be good to have - 
- User has a Dapr v1.8.4 installation at `~/path/.dapr/` with `$DAPR_PATH` set to the same.
- User wants to install v1.7.3 installation at `/tmp/dapr` for testing a behavior change.
- User can run `dapr init --dapr-path /tmp/dapr` without changing the environment variable.

**Comment by mikeb26** [comment]
@shubham1172 @pravinpushkar I like the suggestions to introduce $DAPR_PATH env variable w/ semantic of CLI flag to override. I also like the suggestion to have init throw an explicit error if $HOME/.dapr won't work rather than implicitly fallback to /usr/local/dapr. I'll update https://github.com/dapr/cli/pull/1057 accordingly.

**Comment by berndverst** [comment]
> @shubham1172 @pravinpushkar I like the suggestions to introduce $DAPR_PATH env variable w/ semantic of CLI flag to override. I also like the suggestion to have init throw an explicit error if $HOME/.dapr won't work rather than implicitly fallback to /usr/local/dapr. I'll update #1057 accordingly.

Sounds good to me.

1. No env variable or flag uses HOME folder location
2. If env variable is present (but not CLI flag) that location will be used.
3. If CLI flag is present, always use the location specified via the flag, regardless of env variable.

**Comment by mukundansundar** [comment]
> > @shubham1172 @pravinpushkar I like the suggestions to introduce $DAPR_PATH env variable w/ semantic of CLI flag to override. I also like the suggestion to have init throw an explicit error if $HOME/.dapr won't work rather than implicitly fallback to /usr/local/dapr. I'll update #1057 accordingly.
> 
> Sounds good to me.
> 
> 1. No env variable or flag uses HOME folder location
> 2. If env variable is present (but not CLI flag) that location will be used.
> 3. If CLI flag is present, always use the location specified via the flag, regardless of env variable.

I agree that we have to maintain backwards compatibility and also on the precedence order as described above.

With the introduction of DAPR_PATH this would also fix the https://github.com/dapr/cli/issues/1035 issue of having multiple runtime versions. 

cc @yaron2 any concerns on this?

**Comment by mikeb26** [comment]
https://github.com/dapr/cli/pull/1057 updated as per above

**Comment by yaron2** [comment]
No concerns.
