### ISSUE TITLE
Support passing multiple `--resources-path` flags in `dapr run`

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/cli#1216]
## Describe the proposal

dapr/dapr#5909 is adding the ability to pass multiple `--resources-path` flags in daprd

## Release Note

RELEASE NOTE: **ADD** Support for multiple `--resources-path` flags

**Comment by mukundansundar** [comment]
Once the runtime changes are made, the changes need to be made in CLI as well. This should be changed for the multi-app run template as well.

**Comment by mukundansundar** [comment]
For E2E #904 needs to completed first.

**Comment by mukundansundar** [comment]
This would potentially break multi-app run template as both the template and the run CLI flags share the same underlying struct. 

One potential solution is, continue to keep resourcesPath as string a string variable in the underlying struct. 
```go
ResourcesPath      string            `arg:"resources-path" yaml:"resourcesPath"`
```
So in `dapr run`, users would be able to pass in multiple `--resources-path` flags (`dapr run --resource-path path1 --resources-path path2 --resources-path path3`), but internally represented as `path1,path2,path3` in the struct var `ResourcesPath`. 

This would also mean that in the multi-app run template, the `resourcesPath` field would then accept a `,` delimited string of paths instead of a single path.  (Ideally this should be an array of strings and not a comma separated value of strings)

Or if it is ok to break the template compatibility since this is a preview feature, then we can change this struct value to handle an array of strings as expected. 

In either case, my suggestion for 1.12 will be to completely decouple `dapr run` underlying struct from the multi-app run template file underlying struct and have a translation layer in between. 

cc @ItalyPaleAle @philliphoff @yaron2

**Comment by ItalyPaleAle** [comment]
Could you change the struct used by the multi-app template so `resourcesPath` accepts both a string and an array of strings? This may require changing the type of the property to `any` and then perform run-time type assertions to ensure it's either `string` or `[]string`.

**Comment by mukundansundar** [comment]
> Could you change the struct used by the multi-app template so resourcesPath accepts both a string and an array of strings? This may require changing the type of the property to any and then perform run-time type assertions to ensure it's either string or []string.

Would prefer to have clear types in any struct fields that are going to be unmarshaled from a user input template.

> Would it be crazy to have the template support both the existing resourcesPath string property and a new resourcesPaths array property? The user can choose to use one or the other if there's only a single path, and preserves backward compatibility. (To me, it feels better as a collection should always use plural, even if just specifying one.)

I am not against adding the `resorucesPaths` field ... Just thinking in terms of what if any would be the precedence between `resourcePath` and `resourcesPaths` if both are specified. 
Also consider the multiple `--config` files PR that is pending in `dapr/dapr` In future if that gets added as well shouldn't both `--resources-path` and `--config` follow the same format? 

For normal dapr run the UX would be `dapr run [args] --resources-path path1 --reosurces-path path2` 

For template if adding `resourcesPaths` field, it would follow the same precedence rules as current `resourcesPath` field is following. And between `resourcePaths` and `resourcePath` in the same section, it would follow a clear merge. 
@pravinpushkar since you implemented the parsing and merging logic recently do you seen any difficulties in adding an array `resourcesPaths`?

Should we deprecate the `resourcePath` field in the template then? And remove it shortly... or we can break it and remove it right away ... which I do not want to do ... even if it is a preview feature, there are lots of people using it already. 

cc @ItalyPaleAle @philliphoff @pravinpushkar

**Comment by philliphoff** [comment]
> I am not against adding the `resorucesPaths `field ... Just thinking in terms of what if any would be the precedence between `resourcePath` and `resourcesPaths` if both are specified.

I suppose the *technically* correct thing to do in that case would be to merge them.  That said, I'd also be fine with issuing an error that says one or the other should be used but not both.

> Also consider the multiple `--config` files PR that is pending in `dapr/dapr` In future if that gets added as well shouldn't both `--resources-path` and `--config` follow the same format?

We should aim for consistency whenever possible, unless there's other factors to consider.

> For normal dapr run the UX would be `dapr run [args] --resources-path path1 --reosurces-path path2`

Yes, agree, the CLI should still use singular terms.

> Should we deprecate the `resourcePath` field in the template then? And remove it shortly... or we can break it and remove it right away ... which I do not want to do ... even if it is a preview feature, there are lots of people using it already.

Given it's current use, I'd suggest deprecation rather than outright removal (even considering its preview status).

We *could* always choose to keep it, giving users the choice when they have just a single path to specify.  That's added maintenance cost on us, of course, but might be better UX.  On the other hand, more ways to do the same thing can be additional cognitive load on the user, so 🤷.

**Comment by pravinpushkar** [comment]
> This would potentially break multi-app run template as both the template and the run CLI flags share the same underlying struct.

 
`dapr cli` in the current state (with updated runtime) would accept the single `--resources-path` parameters only. If provided multiple times would take the last parameter. So, We need to enhance the struct to support passing multiple values.

> between resourcePaths and resourcePath in the same section, it would follow a clear merge.

I think we can have the new `resourcesPaths` slice struct field and would pivot to this field for aggregating resources in our implementation.

> Given it's current use, I'd suggest deprecation rather than outright removal (even considering its preview status).

+1

**Comment by mukundansundar** [comment]
> I think we can have the new resourcesPaths slice struct field and would pivot to this field for aggregating resources in our implementation.

Agreed, this has be done is a way that its backwards compatible.
