### ISSUE TITLE
[Proposal] Stop all or specific instance of appID with `dapr stop` command

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/cli#1260]
## Describe the proposal

Today, daparized apps can be run with any one of the following ways - 

1) Standard dapr run command -
`dapr run --app-id test_1`
2) Multi App Run with run config file - 
`dapr run -f dapr.yaml`

Here, Users are allowed to run the same command having same `--app-id(appID for Multi App Run)` multiple times, resulting in having multiple instances of same apps. See the sample `dapr list` output below when `dapr run --app-id test` executed 2 times - 

<img width="1534" alt="Screenshot 2023-03-17 at 10 14 46 AM" src="https://user-images.githubusercontent.com/33649292/225814764-e31ec7a1-f74d-4b71-bcc9-80b006f8f79b.png">

When we execute `dapr stop --app-id test`, it will stop any one of the above instances.

## Solution

We can associate all  `dapr run` runs with unique `runID` which can be of format `${appID}_${randomUniqueID}`. With this we can enhance the `dapr stop` in following way - 

1. `dapr stop --app-id appID || dapr stop appID` -> Will stop all instances of apps with the same app ID. Basically this command will iterate over all the started apps checking for passed appID and trying to stop. Log cumulative errors to console if there are errors while stopping the apps.
2. `dapr stop --run-id runID ` -> will stop a particular instance of dapr run. The `runID` will be stored in metadata and cab fetched from `dapr list` by users. We can also output the runID in logs for easy reference. It will have two execution paths -
       - try to check if started with run file , then fetch process group ID and send interrupt.
       - else execute the normal stop logic by getting the cliPID or daprdPID.

Originally discussed here in this PR - https://github.com/dapr/cli/pull/1205

## Release Note

RELEASE NOTE: **ADD** Enhance `dapr stop` to stop all and any particular instances of apps having same appID

**Comment by mukundansundar** [comment]
Current scenario: 
`dapr stop --app-id <appID>` stops a random app with that ID from the listing.

For enhancements, a couple of points here - 
1. When multiple apps are run with the same `appID`, from individual `dapr run` commands, we need a way to identify that unique app that we want to stop and then stop it. 
2. When multiple apps are run with the same `appID` from a single run template, we need a way to identify that particular instance of app and stop it if needed 
3. We also need a way to stop all apps if needed 

The concept of `runID` would satisfy the requirement 1, but would fail in term of req 2. 

For req 3, we should probably have a `--all` flag in stop to stop all apps with the given `appID` like `dapr stop --app-id <appID> --all`.

But for req 1 and req 2 we need a consistent way to stop individual instances of the app since `appID` is no longer unique.

**Comment by pravinpushkar** [comment]
> 2. When multiple apps are run with the same `appID` from a single run template, we need a way to identify that particular instance of app and stop it if needed

Right, I did not think of this scenario(assumed that a single run file would have all different apps). 
If this is the case then we could take the same approach for both the cases(normal dapr run and Multi app run) - Basically get the daprdPID and appPID and send the interrupt for both the process. We have to leave out the process group PID as that would stop all the instances.



> For req 3, we should probably have a `--all` flag in stop to stop all apps with the given `appID` like `dapr stop --app-id <appID> --all`.

Why `--all` flag is needed. We can modify the current behaviour of `dapr stop --app-id appID` to kill all the instances. Because the current impl itself is not ok.
