### ISSUE TITLE
No error shown if docker containers aren't running

### ISSUE THREAD

**Issue by yaron2** [dapr/cli#200]
## Expected Behavior

CLI should show an error if wasn't able to run Docker containers for Redis and Placement Service during `dapr init`.

## Actual Behavior

Dapr finishes the installation successfully without reporting a problem.

## Steps to Reproduce the Problem

Block access to Docker Hub through a firewall.

First reported here: https://github.com/dapr/docs/issues/232

**Comment by TerraVenil** [comment]
I had the same issue on latest version cli
![image](https://user-images.githubusercontent.com/6068068/68960462-e4223980-07d8-11ea-960f-c6fd1a5587ce.png)
![image](https://user-images.githubusercontent.com/6068068/68960440-da003b00-07d8-11ea-9cf9-6ccedf992cfa.png)
When run `docker inspect`
"Error": "failed to create endpoint dapr_placement on network nat: hnsCall failed in Win32: The process cannot access the file because it is being used by another process. (0x20)"

Just follow https://github.com/docker/for-win/issues/1804#issuecomment-371555979 which fix my issue.
