### ISSUE TITLE
Install fails with "parameter cannot be found that matches parameter name 'DestinationPath'"

### ISSUE THREAD

**Issue by joearias** [dapr/cli#221]
## Expected Behavior
Running ./install/install.ps1 it should successfully install without error.

## Actual Behavior

Receive and exception due to multiple modules with the same command 'Expand-Archive'

iex : A parameter cannot be found that matches parameter name 'DestinationPath'.
At line:1 char:83
+ ... //raw.githubusercontent.com/dapr/cli/master/install/install.ps1 | iex
+                                                                       ~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand

## Steps to Reproduce the Problem

If both Pscx and Microsoft.Powershell.Archive modules are loaded in powershell and run  ./install/install.ps1 
The Pscx module does not support the DestinationPath parameter and you will receive the exception

**Comment by ssimontis** [comment]
You can manually specify that Microsoft.Powershell.Archive is invoked by editing the appropriate JSON file for the installation you are attempting. In my case, I had to edit Solr-SingleDeveloper.json, and change line 110 (under Register.Tasks.ExpandArchive) to have a value of `Microsoft.Powershell.Archive\\Expand-Archive` instead of the original `Expand-Archive`.
