### ISSUE TITLE
Need to be able to point "dapr run" to a manifest directory

### ISSUE THREAD

**Issue by ryanvolum** [dapr/cli#225]
## Describe the proposal

As of now, `dapr init` and `dapr run` automatically create a redis instance (store + pubsub) and the associated manifests in a `components` directory. If we want to use non-Redis components (e.g. CosmosDB), it's unclear how to use them instead of Redis. If we add a `cosmos.yaml` to a pre-existing components directory, a `redis.yaml` still gets created when we run `dapr run`. Further, if we're creating a Kubernetes application that we want to dev/test locally, we probably already have a directory full of manifests that all of our microservices use, and therefore don't want to duplicate those manifests across each microservice's `components` directory. 

## Proposal
@lukekim, @yaron2, as per our conversation and @amanbha's proposal, we should have an optional flag on `dapr run` to pass in a manifest directory (e.g. `../deploy`). Our microservice would then use those components instead of creating a components directory and running/using Redis.

**Comment by ryanvolum** [comment]
Having thought about this a bit more, I think the default behavior of `dapr run` should be to seek out a deploy directory to use, instead of automatically using redis and creating redis manifests. Automatically spinning up and configuring redis (and possibly other stores/components) would be enabled using a flag. This way, the experience across self-hosted mode and kubernetes is the same by default.

Obviously this would represent a major breaking change - just wanted to put it out there. @yaron2, @lukekim, @amanbha let me know what you think.

**Comment by philliphoff** [comment]
To add to this, for new users of Dapr, the relationship between `dapr run` and the (sometimes) scaffolded components isn't very clear.  In particular, if you run the application with `dapr` in different environments (e.g. locally and then in a Dev Container), the application may or may not work depending on whether a components folder has been scaffolded and/or in which environment it was scaffolded.  That is, the scaffolded components contain information about the environment in which `dapr run` was first run, which may not match the environment in which it is later run (either on the same machine at a different time, in a different VM, or on another's machine).  As these files will likely end up in the source repository, the problem can be exacerbated across a team.

I understand that the scaffolded component files intend to serve as a jump point for configuring a "real" store or message bus or other bindings but, for the simple case, it's overkill and just serves as an additional point of failure for the new user.  (And even for experienced users: I consistently fail to remember to update or otherwise re-scaffold these files as I switch environments, such as between the local machine and a Dev Container.)

As @ryanvolum suggests, by default, `dapr run` might *not* scaffold (permanent) component files, but simply configures Redis store/pub-sub bindings by default, based on the current environment (taking into account things such as the DAPR_NETWORK, DAPR_REDIS_HOST, etc. environment variables).  If and when the user has "real" component configuration files, they can simply `dapr run --components <components dir> ...`.  I think this would help provide a more consistent getting started experience.

If users want help scaffolding a "starter" component configuration file, `dapr` could [offer a command to generate them](https://github.com/dapr/cli/issues/234).

**Comment by LMWF** [comment]
This was implemented in #321.
