### ISSUE TITLE
Make cli commands and descriptions consistent

### ISSUE THREAD

**Issue by pruthvidhodda** [dapr/cli#421]
## Describe the proposal

1. Make command descriptions platform agnostic. For example commands like 'init', 'logs', 'mtls' are not specific to k8s so all such descriptions need to corrected.
2. Make nouns consistent for example: Dapr --> dapr, Redis --> redis

**Comment by msfussell** [comment]
This issue is about reviewing all the descriptions AND the help for CLI commands given that
1) Dapr is hosting platform agnostic (There should not be the impression it can only be deployed to Kubernetes)
2) Supports specific hosting platforms (Kubernetes and self hosted) today with new ones being added in the future (e.g. IoT Edge, Docker Swarm etc)
3) Dapr is programming language agnostic
4) Dapr should be written as "Dapr" not "dapr"
4) Redis should be written as "Redis" not "redis"

**For example**
Available Commands:
  init           Setup dapr in Kubernetes or Standalone modes
should say
  init           Installs Dapr on supported hosting platforms

and the help for init should say 
  init           Installs Dapr on supported hosting platforms currently Kubernetes and self hosted

For logs should say (and check help description)
  logs           Gets Dapr sidecar logs for an app 

For mtls should say (and check help description)
  mtls           Check if mTLS is enabled
Note: Should have a conversation with @yaron2 on whether this command can also be applied to self hosted

Effectively review *every* description and help description to ensure these are updated.  For example this (which has inaccuracies)
      --runtime-version string   The version of the Dapr runtime to install. for example: v0.1.0 (default "latest")
should be updated to 
      --runtime-version string   The version of the Dapr runtime to install. For example: "v1.0.0" (default "latest")

**Comment by msfussell** [comment]
Also see bug https://github.com/dapr/cli/issues/455 that can be addressed at the same time, however we should get @yaron2 input on this
