### ISSUE TITLE
Update descriptions that say "Kubernetes cluster" to just say cluster

### ISSUE THREAD

**Issue by msfussell** [dapr/cli#455]
Dapr is hosting platform agnostic and several of the CLI descriptions imply that this could only work on a Kubernetes cluster, when it could in future work on any cluster (e.g. Swarm, Service Fabric etc). These are the descriptions that need to be updated

Currently
  logs           Gets Dapr sidecar logs for an app in Kubernetes
Should be
  logs           Gets Dapr sidecar logs for an app in cluster

Currently
  mtls           Check if mTLS is enabled in a Kubernetes cluster
Should be
  mtls           Check if mTLS is enabled in a cluster

**Comment by yaron2** [comment]
If in the future Dapr will support another cluster type (for example, swarm) we will change the log messages to account for the cluster type name. "in a cluster" is also very unclear to users, they ask themselves which cluster? that's why we have the `--kubernetes` flag that goes along with each of these commands.

So in a Swarm scenario, it would be `dapr mtls --swarm` and an additional description for the flag that says "Check if mTLS is enabled in a Swarm cluster"

**Comment by mukundansundar** [comment]
@msfussell is this issue still relevant?

**Comment by msfussell** [comment]
No. Closed
