### ISSUE TITLE
dapr init for raspberry pi arm doesn't work

### ISSUE THREAD

**Issue by hichamveo** [dapr/cli#460]
HI, i'm facing a problem to init my dapr on linux(raspberry pi 4):

sudo dapr init
⌛  Making the jump to hyperspace...
❌  error downloading dashboard binary: version not found from url: https://github.com/dapr/dashboard/releases/download/v0.2.0/dashboard_linux_arm.tar.gz

also:
sudo dapr init --runtime-version v0.10.0
⌛  Making the jump to hyperspace...
❌  error downloading daprd binary: version not found from url: https://github.com/dapr/dapr/releases/download/vv0.10.0/daprd_linux_arm.tar.gz

dapr --version
CLI version: 0.10.0 
Runtime version: n/a

thanks for help

**Comment by artursouza** [comment]
Try `sudo dapr init --runtime-version 0.10.0`

**Comment by hichamveo** [comment]
already done , but not works. this the 2d part of myquestion.

**Comment by youngbupark** [comment]
@hichamveo sorry for the inconvenience. 0.10.0 docker image for arm has wrong architecture, liunx/amd64, so that docker is unable to find the right os and archtecture images. We fixed the wrong architecture issue of our docker image. 

We will release the final version of 0.11.0 today. Meanwhile please try to install the current pre release version. it should work. 

```
dapr init --runtime-version=0.11.0-rc.4
```

**Comment by youngbupark** [comment]
@hichamveo Please download the latest version(0.11.0) of dapr cli and run `dapr init`. It will work on your RPI 4.

**Comment by hichamveo** [comment]
I confirm now it works fine. thanks for the effort.
