### ISSUE TITLE
Zipkin Docker container image is not installed on ARM deployments with Dapr init command

### ISSUE THREAD

**Issue by msfussell** [dapr/cli#500]
Need to determine what tracing tech is deployed on ARM if Zipkin cannot be installed due to no ARM container image. See this issue https://github.com/openzipkin/zipkin/issues/3141

**Comment by artursouza** [comment]
The issue has been solved in by Zipkin. Since we reference the latest image, instead of a particular version, we got the fix for "free". I have validated with dapr cli 0.11 on my Raspberry PI and `dapr init` works. I have also tested with the observability quickstart in the K3s Pi cluster and zipkin starts as well. I am closing this.

**Comment by Zigby** [comment]
Is ARMV7 not supported? 
I tried using Raspian and it did not work
![image](https://user-images.githubusercontent.com/28486683/104135016-9fb70d00-538d-11eb-906e-45d609ef5a1c.png)
![image](https://user-images.githubusercontent.com/28486683/104134962-4d75ec00-538d-11eb-89c1-7d035a3b0ccf.png)
Are you using a 64 bit OS on Raspberry Pi?

**Comment by artursouza** [comment]
Yes, I used ARM64. Zipkin's image only works on ARM64 and AMD64: https://hub.docker.com/layers/openzipkin/zipkin/latest/images/sha256-7fb58f06f16299a525f7bf15f84c007af1dc860c8f4122c5cff3750e7ad4c342?context=explore
