### ISSUE TITLE
Failed to upgrade Dapr: release name is invalid

### ISSUE THREAD

**Issue by javageek79** [dapr/cli#649]
## Expected Behavior

successfull dapr upgrade from 1.0.0.-rc4 to 1.0.1 via cli

## Actual Behavior

dapr upgrade terminates with the following message.

`"Failed to upgrade Dapr: release name is invalid:  "`

## Steps to Reproduce the Problem

run
```
dapr upgrade \
--kubernetes \ 
--runtime-version=1.0.1 \
--set dapr_operator.resources.requests.cpu=100m  \
--set dapr_operator.resources.requests.memory=100Mi  \
--set dapr_operator.resources.limits.cpu=1  \
--set dapr_operator.resources.limits.memory=200Mi  \
--set dapr_dashboard.resources.requests.cpu=50m  \
--set dapr_dashboard.resources.requests.memory=20Mi  \
--set dapr_dashboard.resources.limits.cpu=200m  \
--set dapr_dashboard.resources.limits.memory=200Mi  \
--set dapr_placement.resources.requests.cpu=250m  \
--set dapr_placement.resources.requests.memory=75Mi  \
--set dapr_placement.resources.limits.cpu=1  \
--set dapr_placement.resources.limits.memory=500Mi  \
--set dapr_sentry.resources.requests.cpu=100m  \
--set dapr_sentry.resources.requests.memory=30Mi  \
--set dapr_sentry.resources.limits.cpu=1  \
--set dapr_sentry.resources.limits.memory=200Mi  \
--set dapr_sidecar_injector.resources.requests.cpu=100m  \
--set dapr_sidecar_injector.resources.requests.memory=30Mi  \
--set dapr_sidecar_injector.resources.limits.cpu=1  \
--set dapr_sidecar_injector.resources.limits.memory=200Mi \
```

The same upgrade command has been successfully executed on two other environments already. 

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
Hi @javageek79 I am seeing that the error you are getting is related to the release name. Could you check what release name you have for the environment?

**Comment by javageek79** [comment]
we tried to run the upgrade via helm directly. So the actual error was revealed.
![image2021-4-6_18-2-45](https://user-images.githubusercontent.com/3714921/113835158-fb761400-978b-11eb-8529-907960aa7d9e.png)

**Comment by artursouza** [comment]
@javageek79 Thanks for bringing this up.

1. `replicas` can be changed if you switch between HA mode on/off in your flags. See the Helm chart template below:
```
{{- if eq .Values.global.ha.enabled true }}
  replicas: {{ .Values.global.ha.replicaCount }}
{{- else }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
```

2. `template` can be modified based on multiple params you might set, see https://github.com/dapr/dapr/blob/master/charts/dapr/charts/dapr_placement/templates/dapr_placement_deployment.yaml

3. `updateStrategy` is not in the template above, so it is unlikely to be the root cause.

If the parameters being passed via helm have changed, then this error might occur. To force the update (with outage in actor invocation), try deleting placement service before the upgrade.

**Comment by mukundansundar** [comment]
@javageek79 can this issue be closed?

**Comment by javageek79** [comment]
Yes
