### ISSUE TITLE
[Proposal] Create standalone installer

### ISSUE THREAD

**Issue by wcs1only** [dapr/cli#731]
## Describe the proposal

We can create a standalone install package with ```dapr``` CLI and ```daprd``` binary and perhaps the docker containers we need. The idea being, a package that you can self-host/cache somewhere and deploy dapr without depending on the github API. 

We could create Windows, Mac, and Linux installers.

## Release Note

RELEASE NOTE:

**Comment by daixiang0** [comment]
It sounds like alternative as offline deploy, we can download it and deploy without network.

**Comment by artursouza** [comment]
I would reuse `dapr init` to do this job and enable to pass in an URL (or local path) to a tar file with "everything" in it.

**Comment by mukundansundar** [comment]
related to #640

**Comment by beiwei30** [comment]
@shivamkm07 You may consider to help enhancing #898, thanks :)

**Comment by shivamkm07** [comment]
Thank you [@beiwei30](https://github.com/beiwei30) for your contributions. We can handle the scenario in different ways. Below are the possible designs for the installer(Changes in https://github.com/dapr/cli/pull/898 are presented as 3rd design):

# DAPR standalone installer for airgap environments 

Purpose: To support DAPR installed and running in the isolated environments where there is no internet connectivity.  

In the current scenarios user must install Dapr CLI first and then run `dapr init` to load all the needed artifacts to run DAPR in the given environments:

1.  Downloads binaries(daprd, dashboard) and places them in right directory
2. Downloads daprio/placement and runs the container
3. Downloads openzipkin/zipkin and redis images and runs the containers
4. Slim installation(`dapr init -s`) installs binaries without loading any containers

Airgap/Standalone installer is also expected to support all the above 4 steps

# Design 

There are 3 approaches that we can generate the standalone installer. 

## Design 1

1. All required binaries(cli, daprd, dashboard) and daprio/placement image are downloaded and combined into one executable `standalone`(e.g., dapr-standalone.exe)
2. On execution, `standalone` installs binaries and loads placement container by default
3. Third party images(redis, zipkin) are not bundled with `standalone` since that would require a new version of executable to be released with every new version of redis or zipkin.
4. User can either manually pull and run the redis and zipkin containers or provide path to saved images to executable to load them up
5. Slim installation would also be supported, in which only binaries would be installed
6. A separate `standalone` repo to handle the dependencies across repositories as this standalone installer depends on dapr runtime, dashboard as well as CLI releases.

**Pros**:
1.   Relatively easy dev experience for the user, since all images/binaries are combined into one single executable
2. No dependency on zipkin/redis releases

**Cons**: 
1. There is a bit of code duplication, which might require further maintenance as and when there are some changes to `dapr init`
2. This would lead to having two executables for installing dapr: `dapr` cli and `standalone`
3. User must manually download redis/zipkin images and run the containers

### Commands
./standalone  [--slim] [--path-to-images images/]      # Installs binaries and loads placement container, images/ contain downloaded zipkin and redis images

## Design 2

1) All required binaries(cli, daprd, dashboard) and daprio/placement image are downloaded and released as one bundled artifact, structured as a zipped folder `dapr-bundle`
2) User downloads the released artifact and runs enchanced `dapr init`(see commands) itself to install the binaries including cli and load placement container. While currently `dapr init` downloads binaries from github, the enhanced version will override the behavior and load them up from the `dapr-bundle` when provided.
3) Third party images(redis, zipkin) are not bundled in the artifact since that would require a new version of executable to be released with every new version of redis or zipkin.
4) User can either manually pull and run redis/zipkin containers or add saved images in `images/` folder mentioned below(see commands)
5) Slim installation is by default supported in `dapr init`
6) A separate `standalone` repo to handle the dependencies across repositories as this standalone installer depends on dapr runtime, dashboard as well as CLI releases.

### Artifact Structure

Artifact would be structured as follows:
- dapr-bundle/
  - bin/
    | dapr
    | daprd
    | dashboard
  - images/
    | placement-1.6.0.tar.gz

**Pros**:
1. Decoupling of `dapr` CLI with the `dapr-bundle` would lead to better long term code maintenance
2. No dependency on zipkin/redis releases
3. A consistent user experience, since `dapr init` itself would be used to install dapr in airgap mode as well

**Cons**:
1. Setup in airgap mode would be relatively more involved
2. User must manually download redis/zipkin images and run the containers

### Commands
./dapr-bundle/bin/dapr init [--slim] [--path-to-binaries bin/] [--path-to-images images/]  #Installs binaries located in /bin and loads and run containers in images/

// To load redis and zipkin, either they can be run manually or the saved tar.gz files can be added in images/ folder

## Design 3

https://github.com/dapr/cli/pull/898 describes another possible way of having airgap installation

1) A fat/airgap CLI binary would be released bundling all binaries as well as images(e.g. airgap-dapr.exe)
2) User has to run `dapr init` using airgap CLI to have all the binaries installed as well as the containers loaded up
3) Slim installation would be by default supported
4) No separate repo, since airgap CLI would be released from CLI release workflow itself

**Pros**:
1. Consistent and easiest dev experience, just using `dapr init` without any extra flags etc. would do the airgap installation
2. User won't need to manually pull redis/zipkin images since they would be bundled as well in airgap CLI

**Cons**:
1. Without having a separate repo, for every release/hotfix in dapr runtime/dashboard, a new version of CLI would need to be released
2. `airgap CLI` is just required for installing dapr, after that user can do away with using normal CLI binary, instead of the big fat airgap binary
3. For every redis/zipkin release, a new version of airgap CLI would need to be released due to the dependency

### Commands
./airgap-dapr init [--slim] 

Let us collaborate further to finalize the solution.

**Comment by shivamkm07** [comment]
FYI, following PRs resolve the issue:
Release workflow: https://github.com/dapr/installer-bundle/pull/1
Enhancing Dapr CLI: https://github.com/dapr/cli/pull/898

@artursouza this can be closed now.

**Comment by mukundansundar** [comment]
> FYI, following PRs resolve the issue: Release workflow: [dapr/installer-bundle#1](https://github.com/dapr/installer-bundle/pull/1) Enhancing Dapr CLI: #898
> 
> @artursouza this can be closed now.

closing.

**Comment by msfussell** [comment]
@shivamkm07 - Please complete the documentation for the feature. This issue https://github.com/dapr/docs/issues/2299
