### ISSUE TITLE
Provide an option for non-root install.

### ISSUE THREAD

**Issue by brendandburns** [dapr/cli#79]
running `actions init` tries to copy something into a privileged location (`/usr/local/bin`) that's fine, but you might want to:

a) print a more useful error message (e.g. 'sudo actions init') instead of just failing the write.

b) provide a command line option for saving to an alternate location so that people w/o root can still install.

**Comment by yaron2** [comment]
How about we change from from `/usr/local/bin` to `$HOME/.dapr/bin` and instruct users to add to path with:

```
export PATH=$PATH:$HOME/.dapr/bin
```

**Comment by LMWF** [comment]
Combining the two suggestions - how about:
1) If `dapr init` fails to copy to the default location (`/usr/local/bin`) print a better message e.g `Cannot write to /usr/local/bin, please run sudo dapr init`.
2) Add an optional arg to `dapr init`, --install-path, to install to a user-provided location instead of `/usr/local/bin` & include output at the end to add the specified location to the path:
```
!!!dapr installed to [user-provided location], please run the following to add it to your path:

    export PATH=$PATH:[user-provided location]
```

**Comment by LMWF** [comment]
Related issue: https://github.com/dapr/cli/issues/168
