### ISSUE TITLE
get components-path from environment variable

### ISSUE THREAD

**Issue by aktxyz** [dapr/cli#799]
## Describe the proposal

In this issue, the idea of adding CLI control for the component-path was brought up and implemented.
https://github.com/dapr/cli/issues/321

Was there any consideration for also allowing this to be set via an environment variable?  I know that making everything setting via envvar is not great, but having this path may be worth it.

The scenario for me boils down to a local dev workflow where it would be convenient to use env vars instead of CLI options to flip between setups.  I currently have some scripts that invoke the cli, and the scripts pick up an env var and apply via the CLI, so have my flow working well.  But thought I would put this out there to get thoughts.

**Comment by mukundansundar** [comment]
@aktxyz The components will differ for every dapr application. Hence providing it as an environment variable(Since in one shell we might run different apps at different points in time) might not be the right approach except for default path config which is already available. 

@yaron2 any thoughts on this?
