### ISSUE TITLE
Partition Key in Azure Cosmos DB using Dapr Sidecar

### ISSUE THREAD

**Issue by ghost** [dapr/cli#805]
> /area runtime

> /area operator

> /area placement

> /area docs

> /area test-and-release

I am having trouble adding a custom partition key to Azure Cosmos DB using Dapr sidecar.
Here is my Azure Cosmos DB instance:
![image](https://user-images.githubusercontent.com/44985701/136269890-3627b253-9fbe-44ff-9011-4cf3f19a863e.png)

From the documentation, I have named my partitionKey as /id. However, when I try to add a custom partition key value, I get this error:
![image](https://user-images.githubusercontent.com/44985701/136270390-1fcbe226-912e-4124-a665-33f99d0d9612.png)

Dapr Version Info:
dapr -v
CLI version: 1.3.0
Runtime version: 1.4.0

**Comment by CodeMonkeyLeet** [comment]
@dasaraiy, there seem to be a couple of things going on here:

1. It looks like you're invoking this directly through powershell, so this issue probably doesn't belong in the CLI repo and might have better traction under dapr/components-contrib. 

2. There's an expectation that the using the `partitionKey` metadata adds a custom partition key value independent of the body of the message. Per the returned error https://aka.ms/CosmosDB/sql/errors/wrong-pk-value, CosmosDB still expects that the `partitionKey` value specified has to match the actual value extracted from the body of the message for that given partition key. This could be a documentation issue with https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-azure-cosmosdb/#partition-keys and it's unclear that cosmos DB accepts the example provided there.

3. In the specific case of this issue where collection's partition key is defined as "/id" in the give repro, it would be redundant to specify metadata `partitionKey` since it would have to match the `id` value (which is specified by the `key` property in the http body in the example). It's a doubly non-obvious use because the state store component prefixes the key value with the name of the app (e.g. "myapp||nihilus") so for the given example to succeed the message would have to be something like:

    ```bash
    curl -X POST http://localhost:3500/v1.0/state/statestore -H "Content-Type: application/json" -d '[{"key": "nihilus", "value": "darth", "metadata": { "partitionKey": "myapp||nihilus" }}]'
    ```
  
    which would have the same result as omitting the metadata section entirely: 
  
    ```bash 
    curl -X POST http://localhost:3500/v1.0/state/statestore -H "Content-Type: application/json" -d '[{"key": "nihilus", "value": "darth"}]'
    ```
