### ISSUE TITLE
proposal: "dapr init" add  "--image-repository"

### ISSUE THREAD

**Issue by zgfh** [dapr/cli#869]
## Describe the proposal
dapr init should have param of "--image-repository" to set image repository
He is very helpful to many people who cannot access the direct external network

## Release Note

RELEASE NOTE: "dapr init" ADD  "--image-repository"

**Comment by mukundansundar** [comment]
related to #640

**Comment by artursouza** [comment]
Does this issue allow download of 3rd party images too? Like redis and zipkin. Do we still have those hardcoded?

**Comment by pravinpushkar** [comment]
@artursouza  Yes, the images are still hardcoded. If the private/custom registry mirrors the dockerhub exactly then this command would be able to download the 3rd party images too along with placement. The current solution has this limitation for now. 

The fact that cli needs different images which can be under different org/path in private registries, the complete url to pull from could be different for each. We need more robust solution along with default hardcoded images(either from docker/ghcr). So that `dapr init` remain as simple as it is today without the need for multiple flags even for private registries.
