### ISSUE TITLE
dapr init --slim gives me - error moving dashboard.exe binary to path: rename

### ISSUE THREAD

**Issue by AvtsVivek** [dapr/cli#963]
As per the suggestion [here](https://github.com/dapr/samples/issues/97#issuecomment-1094259195), I am raising a new issue
I am trying to do [this dapr slim sample](https://github.com/dapr/samples/tree/master/hello-dapr-slim).

I ensure a clean slate by running dapr uninstall --all.

Then I start with [the first step of Slim Init](https://github.com/dapr/samples/tree/master/hello-dapr-slim#step-1---setup-dapr-slim-init).

`error moving dashboard.exe binary to path: rename C:\Users\UserName\.dapr\bin\release\windows_amd64\dashboard.exe C:\Users\UserName\.dapr\bin\dashboard.exe: Access is denied.`

Note below I am running powershell as administrator.

![image](https://user-images.githubusercontent.com/41255281/150289490-5b9257fb-3297-4507-841e-255a115186bf.png)

What am I missing?

**Comment by shivamkm07** [comment]
As per the discussion [here](https://github.com/dapr/samples/issues/97), the issue is happening because there was dashboard running in the background, and so windows couldn't remove the dashboard binary while uninstalling (There is a warning message stating the same during uninstall). And so, when `dapr init` is tried, it throws error. 

Note that the behavior is specific to windows, as in Linux, u can delete a binary even if a process is running in the background while in windows u can't. So, the error looks expected to me.  Thoughts?

**Comment by mukundansundar** [comment]
@AvtsVivek Was this issue resolved ?
